backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads
logo_url: https://your-site.com/images/logo.svg
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    folder: 'docs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'sidebar' # Used in routes, e.g., /admin/collections/blog
    label: 'Sidebar' # Used in the UI
    folder: 'docs/sidebar' # The path to the folder where the documents are stored
    delete: false
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'test' # Used in routes, e.g., /admin/collections/blog
    label: 'Test' # Used in the UI
    folder: 'docs' # The path to the folder where the documents are stored
    delete: false
    format: md
    frontmatter_delimiter: '~~~'
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'test2' # Used in routes, e.g., /admin/collections/blog
    label: 'Test2' # Used in the UI
    folder: 'docs' # The path to the folder where the documents are stored
    delete: false
    format: md
    frontmatter_delimiter: ['[comment]: # (', ')']
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
